openapi: 3.1.0
info:
  description: Spring API
  title: Spring API
  version: 1.0.0
servers:
- url: https://Spring
paths:
  /event:
    get:
      operationId: getAllEvents
      responses:
        "200":
          content:
            '*/*':
              schema:
                type: string
          description: OK
      summary: GET event
      x-accepts:
      - '*/*'
components:
  schemas: {}

